In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
# Import the dataa

df = pd.read_csv("telecom_extract_SQL.csv")

In [24]:
df.head(10)

,customer_id,gender,senior_citizen,partner,dependents,signup_date,tenure_months,contract_type,paperless_billing,payment_method,monthly_charges,total_charges,churn,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,total_tickets,avg_satisfaction_score,avg_monthly_data_gb,avg_monthly_call_minutes
0,0002-ORFBO,Female,0,Yes,Yes,2023-10-04,9,One year,Yes,Mailed check,65.60,593.30,No,Yes,No,DSL,No,Yes,No,Yes,Yes,No,0,NaN,93.13333,769.11111
1,0003-MKNFE,Male,0,No,No,2023-10-04,9,Month-to-month,No,Mailed check,59.90,542.40,No,Yes,Yes,DSL,No,No,No,No,No,Yes,2,3.0000,65.21111,598.55556
2,0004-TLHLJ,Male,0,No,No,2024-03-02,4,Month-to-month,Yes,Electronic check,73.90,280.85,Yes,Yes,No,Fiber optic,No,No,Yes,No,No,No,1,1.0000,84.07500,445.50000
3,0011-IGKFF,Male,1,Yes,No,2023-06-06,13,Month-to-month,Yes,Electronic check,98.00,1237.85,Yes,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,3,1.6667,56.06923,539.07692
4,0013-EXCHZ,Female,1,Yes,No,2024-04-01,3,Month-to-month,Yes,Mailed check,83.90,267.40,Yes,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,3,3.3333,90.06667,634.00000
5,0013-MHZWF,Female,0,No,Yes,2023-10-04,9,Month-to-month,Yes,Credit card (automatic),69.40,571.45,No,Yes,No,DSL,No,No,No,Yes,Yes,Yes,3,3.0000,82.60000,465.77778
6,0013-SMEOE,Female,1,Yes,No,2018-08-31,71,Two year,Yes,Bank transfer (automatic),109.70,7904.25,No,Yes,No,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,0,NaN,86.87083,602.62500
7,0014-BMAQU,Male,0,Yes,No,2019-04-28,63,Two year,Yes,Credit card (automatic),84.65,5377.80,No,Yes,Yes,Fiber optic,Yes,No,No,Yes,No,No,0,NaN,72.71667,723.04167
8,0015-UOCOJ,Female,1,No,No,2023-12-03,7,Month-to-month,Yes,Electronic check,48.20,340.35,No,Yes,No,DSL,Yes,No,No,No,No,No,1,3.0000,45.38571,533.42857
9,0016-QLJIS,Female,0,Yes,Yes,2019-02-27,65,Two year,Yes,Mailed check,90.45,5957.90,No,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,0,NaN,82.75833,619.45833

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               7043 non-null   object
 1   gender                    7043 non-null   object
 2   senior_citizen            7043 non-null   int64
 3   partner                   7043 non-null   object
 4   dependents                7043 non-null   object
 5   signup_date               7043 non-null   object
 6   tenure_months             7043 non-null   int64
 7   contract_type             7043 non-null   object
 8   paperless_billing         7043 non-null   object
 9   payment_method            7043 non-null   object
 10  monthly_charges           7043 non-null   float64
 11  total_charges             7043 non-null   float64
 12  churn                     7043 non-null   object
 13  phone_service             7043 non-null   object
 14  multiple_lines            7043 non-null   object
 15  internet_service          7043 non-null   object
 16  online_security           7043 non-null   object
 17  online_backup             7043 non-null   object
 18  device_protection         7043 non-null   object
 19  tech_support              7043 non-null   object
 20  streaming_tv              7043 non-null   object
 21  streaming_movies          7043 non-null   object
 22  total_tickets             7043 non-null   int64
 23  avg_satisfaction_score    5268 non-null   float64
 24  avg_monthly_data_gb       7032 non-null   float64
 25  avg_monthly_call_minutes  7032 non-null   float64
dtypes: float64(5), int64(3), object(18)
memory usage: 1.4+ MB

In [26]:
print(df.shape)

(7043, 26)

In [27]:
print(df.isnull().sum())

customer_id                    0
gender                         0
senior_citizen                 0
partner                        0
dependents                     0
signup_date                    0
tenure_months                  0
contract_type                  0
paperless_billing              0
payment_method                 0
monthly_charges                0
total_charges                  0
churn                          0
phone_service                  0
multiple_lines                 0
internet_service               0
online_security                0
online_backup                  0
device_protection              0
tech_support                   0
streaming_tv                   0
streaming_movies               0
total_tickets                  0
avg_satisfaction_score      1775
avg_monthly_data_gb           11
avg_monthly_call_minutes      11
dtype: int64

In [28]:
print(df.duplicated().sum())

0

In [29]:
df.describe()

,senior_citizen,tenure_months,monthly_charges,total_charges,total_tickets,avg_satisfaction_score,avg_monthly_data_gb,avg_monthly_call_minutes
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,5268.000000,7032.000000,7032.000000
mean,0.162147,32.371149,64.761692,2279.798992,1.494392,3.003923,75.374365,622.988373
std,0.368612,24.559481,30.090047,2266.730170,1.185238,1.121862,17.543774,135.981502
min,0.000000,0.000000,18.250000,18.800000,0.000000,1.000000,1.400000,51.000000
25%,0.000000,9.000000,35.500000,398.550000,0.000000,2.000000,67.722917,564.656252
50%,0.000000,29.000000,70.350000,1394.550000,1.000000,3.000000,75.466670,623.416665
75%,0.000000,55.000000,89.850000,3786.600000,2.000000,4.000000,83.033330,683.186365
max,1.000000,72.000000,118.750000,8684.800000,4.000000,5.000000,149.600000,1197.000000

In [30]:
# Change the datatype of signup_date (Object => datetime)

df["signup_date"] = pd.to_datetime(df["signup_date"], errors = "coerce").fillna("Invalid Date")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               7043 non-null   object
 1   gender                    7043 non-null   object
 2   senior_citizen            7043 non-null   int64
 3   partner                   7043 non-null   object
 4   dependents                7043 non-null   object
 5   signup_date               7043 non-null   datetime64[ns]
 6   tenure_months             7043 non-null   int64
 7   contract_type             7043 non-null   object
 8   paperless_billing         7043 non-null   object
 9   payment_method            7043 non-null   object
 10  monthly_charges           7043 non-null   float64
 11  total_charges             7043 non-null   float64
 12  churn                     7043 non-null   object
 13  phone_service             7043 non-null   object
 14  multiple_lines            7043 non-null   object
 15  internet_service          7043 non-null   object
 16  online_security           7043 non-null   object
 17  online_backup             7043 non-null   object
 18  device_protection         7043 non-null   object
 19  tech_support              7043 non-null   object
 20  streaming_tv              7043 non-null   object
 21  streaming_movies          7043 non-null   object
 22  total_tickets             7043 non-null   int64
 23  avg_satisfaction_score    5268 non-null   float64
 24  avg_monthly_data_gb       7032 non-null   float64
 25  avg_monthly_call_minutes  7032 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(3), object(17)
memory usage: 1.4+ MB

In [31]:
# I have created this column for which customer who has raise a support_ticket or not
df['has_support_ticket'] = df['avg_satisfaction_score'].notnull().map({True: 'Yes', False: 'No'})
# avg_satisfaction_score ko fillna mat karo - blank/NaN hi rehne do

# usage columns pe 0 hi theek hai (genuinely zero, numeric issue nahi hoga)
df['avg_satisfaction_score'] = df['avg_satisfaction_score'].fillna(0)
df['avg_monthly_data_gb'] = df['avg_monthly_data_gb'].fillna(0)
df['avg_monthly_call_minutes'] = df['avg_monthly_call_minutes'].fillna(0)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               7043 non-null   object
 1   gender                    7043 non-null   object
 2   senior_citizen            7043 non-null   int64
 3   partner                   7043 non-null   object
 4   dependents                7043 non-null   object
 5   signup_date               7043 non-null   datetime64[ns]
 6   tenure_months             7043 non-null   int64
 7   contract_type             7043 non-null   object
 8   paperless_billing         7043 non-null   object
 9   payment_method            7043 non-null   object
 10  monthly_charges           7043 non-null   float64
 11  total_charges             7043 non-null   float64
 12  churn                     7043 non-null   object
 13  phone_service             7043 non-null   object
 14  multiple_lines            7043 non-null   object
 15  internet_service          7043 non-null   object
 16  online_security           7043 non-null   object
 17  online_backup             7043 non-null   object
 18  device_protection         7043 non-null   object
 19  tech_support              7043 non-null   object
 20  streaming_tv              7043 non-null   object
 21  streaming_movies          7043 non-null   object
 22  total_tickets             7043 non-null   int64
 23  avg_satisfaction_score    7043 non-null   float64
 24  avg_monthly_data_gb       7043 non-null   float64
 25  avg_monthly_call_minutes  7043 non-null   float64
 26  has_support_ticket        7043 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(3), object(18)
memory usage: 1.5+ MB

In [33]:
df.head(5)

,customer_id,gender,senior_citizen,partner,dependents,signup_date,tenure_months,contract_type,paperless_billing,payment_method,monthly_charges,total_charges,churn,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,total_tickets,avg_satisfaction_score,avg_monthly_data_gb,avg_monthly_call_minutes,has_support_ticket
0,0002-ORFBO,Female,0,Yes,Yes,2023-10-04,9,One year,Yes,Mailed check,65.6,593.30,No,Yes,No,DSL,No,Yes,No,Yes,Yes,No,0,0.0000,93.13333,769.11111,No
1,0003-MKNFE,Male,0,No,No,2023-10-04,9,Month-to-month,No,Mailed check,59.9,542.40,No,Yes,Yes,DSL,No,No,No,No,No,Yes,2,3.0000,65.21111,598.55556,Yes
2,0004-TLHLJ,Male,0,No,No,2024-03-02,4,Month-to-month,Yes,Electronic check,73.9,280.85,Yes,Yes,No,Fiber optic,No,No,Yes,No,No,No,1,1.0000,84.07500,445.50000,Yes
3,0011-IGKFF,Male,1,Yes,No,2023-06-06,13,Month-to-month,Yes,Electronic check,98.0,1237.85,Yes,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,3,1.6667,56.06923,539.07692,Yes
4,0013-EXCHZ,Female,1,Yes,No,2024-04-01,3,Month-to-month,Yes,Mailed check,83.9,267.40,Yes,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,3,3.3333,90.06667,634.00000,Yes

In [34]:
# 1. Tenure ko readable buckets mein toda (dashboard filter ke liye)
def tenure_bucket(months):
    if months <= 12:
        return "0-1 Year"
    elif months <= 24:
        return "1-2 Years"
    elif months <= 36:
        return "2-3 Years"
    elif months <= 48:
        return "3-4 Years"
    else:
        return "4+ Years"

df['tenure_bucket'] = df['tenure_months'].apply(tenure_bucket)

In [35]:
# 2. Revenue at risk - agar customer churn kar jaye to kitna annual revenue loss hoga
df['annual_revenue_at_risk'] = np.where(df['churn'] == 'Yes', df['monthly_charges'] * 12, 0)

In [36]:
# 4. Total services subscribed count (kitne add-ons liye hain - engagement signal)
addon_cols = ['online_security','online_backup','device_protection',
              'tech_support','streaming_tv','streaming_movies']
df['total_addons_subscribed'] = df[addon_cols].apply(
    lambda row: sum(1 for v in row if v == 'Yes'), axis=1
)

In [37]:
# 5. Churn ko readable binary flag bhi bana lo (dashboard KPI cards ke liye easy)
df['is_churned'] = df['churn'].map({'Yes': 1, 'No': 0})

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               7043 non-null   object
 1   gender                    7043 non-null   object
 2   senior_citizen            7043 non-null   int64
 3   partner                   7043 non-null   object
 4   dependents                7043 non-null   object
 5   signup_date               7043 non-null   datetime64[ns]
 6   tenure_months             7043 non-null   int64
 7   contract_type             7043 non-null   object
 8   paperless_billing         7043 non-null   object
 9   payment_method            7043 non-null   object
 10  monthly_charges           7043 non-null   float64
 11  total_charges             7043 non-null   float64
 12  churn                     7043 non-null   object
 13  phone_service             7043 non-null   object
 14  multiple_lines            7043 non-null   object
 15  internet_service          7043 non-null   object
 16  online_security           7043 non-null   object
 17  online_backup             7043 non-null   object
 18  device_protection         7043 non-null   object
 19  tech_support              7043 non-null   object
 20  streaming_tv              7043 non-null   object
 21  streaming_movies          7043 non-null   object
 22  total_tickets             7043 non-null   int64
 23  avg_satisfaction_score    7043 non-null   float64
 24  avg_monthly_data_gb       7043 non-null   float64
 25  avg_monthly_call_minutes  7043 non-null   float64
 26  has_support_ticket        7043 non-null   object
 27  tenure_bucket             7043 non-null   object
 28  annual_revenue_at_risk    7043 non-null   float64
 29  total_addons_subscribed   7043 non-null   int64
 30  is_churned                7043 non-null   int64
dtypes: datetime64[ns](1), float64(6), int64(5), object(19)
memory usage: 1.7+ MB

In [39]:
pd.set_option('display.max_columns', None)
df.head(10)

,customer_id,gender,senior_citizen,partner,dependents,signup_date,tenure_months,contract_type,paperless_billing,payment_method,monthly_charges,total_charges,churn,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,total_tickets,avg_satisfaction_score,avg_monthly_data_gb,avg_monthly_call_minutes,has_support_ticket,tenure_bucket,annual_revenue_at_risk,total_addons_subscribed,is_churned
0,0002-ORFBO,Female,0,Yes,Yes,2023-10-04,9,One year,Yes,Mailed check,65.60,593.30,No,Yes,No,DSL,No,Yes,No,Yes,Yes,No,0,0.0000,93.13333,769.11111,No,0-1 Year,0.0,3,0
1,0003-MKNFE,Male,0,No,No,2023-10-04,9,Month-to-month,No,Mailed check,59.90,542.40,No,Yes,Yes,DSL,No,No,No,No,No,Yes,2,3.0000,65.21111,598.55556,Yes,0-1 Year,0.0,1,0
2,0004-TLHLJ,Male,0,No,No,2024-03-02,4,Month-to-month,Yes,Electronic check,73.90,280.85,Yes,Yes,No,Fiber optic,No,No,Yes,No,No,No,1,1.0000,84.07500,445.50000,Yes,0-1 Year,886.8,1,1
3,0011-IGKFF,Male,1,Yes,No,2023-06-06,13,Month-to-month,Yes,Electronic check,98.00,1237.85,Yes,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,3,1.6667,56.06923,539.07692,Yes,1-2 Years,1176.0,4,1
4,0013-EXCHZ,Female,1,Yes,No,2024-04-01,3,Month-to-month,Yes,Mailed check,83.90,267.40,Yes,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,3,3.3333,90.06667,634.00000,Yes,0-1 Year,1006.8,2,1
5,0013-MHZWF,Female,0,No,Yes,2023-10-04,9,Month-to-month,Yes,Credit card (automatic),69.40,571.45,No,Yes,No,DSL,No,No,No,Yes,Yes,Yes,3,3.0000,82.60000,465.77778,Yes,0-1 Year,0.0,3,0
6,0013-SMEOE,Female,1,Yes,No,2018-08-31,71,Two year,Yes,Bank transfer (automatic),109.70,7904.25,No,Yes,No,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,0,0.0000,86.87083,602.62500,No,4+ Years,0.0,6,0
7,0014-BMAQU,Male,0,Yes,No,2019-04-28,63,Two year,Yes,Credit card (automatic),84.65,5377.80,No,Yes,Yes,Fiber optic,Yes,No,No,Yes,No,No,0,0.0000,72.71667,723.04167,No,4+ Years,0.0,2,0
8,0015-UOCOJ,Female,1,No,No,2023-12-03,7,Month-to-month,Yes,Electronic check,48.20,340.35,No,Yes,No,DSL,Yes,No,No,No,No,No,1,3.0000,45.38571,533.42857,Yes,0-1 Year,0.0,1,0
9,0016-QLJIS,Female,0,Yes,Yes,2019-02-27,65,Two year,Yes,Mailed check,90.45,5957.90,No,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,0,0.0000,82.75833,619.45833,No,4+ Years,0.0,6,0

In [40]:
# Export the data

df.to_csv("telecom_churn_cleaned.csv", index=False)
print("Cleaned file saved! Shape:", df.shape)

Cleaned file saved! Shape: (7043, 31)